exec SP_INSERT_CIDADE @NM_CIDADE = 'Abadia de Goias';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abadia dos Dourados';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abadiania';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abaete';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abaetetuba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abaiara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abaira';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abare';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abatia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abdon Batista';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abel Figueiredo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abelardo Luz';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abre Campo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abreu e Lima';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abreulandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acaiaca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acailandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acajutiba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acarape';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acarau';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acari';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acaua';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acegua';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acopiara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acorizal';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acrelandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acreuna';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acu';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acucena';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Adamantina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Adelandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Adolfo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Adrianopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Adustina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afogados da Ingazeira';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afonso Bezerra';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afonso Claudio';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afonso Cunha';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afranio';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afuá';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agrestina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agricolandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agrolandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agronomica';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Azul do Norte';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Boa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Boa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Branca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Branca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Branca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Clara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Comprida';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Doce';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Doce do Maranhao';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Doce do Norte';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Fria';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Fria de Goias';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Limpa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Nova';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Preta';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Santa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguaí';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguanil';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas Belas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas da Prata';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas de Chapeco';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas de Lindoi';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas de Santa Barbara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas de Sao Pedro';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas Formosas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas Frias';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas Lindas de Goias';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas Mornas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguas Vermelhas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agudo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agudos';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agudos do Sul';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguia Branca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguiar';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguiarnopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aimores';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aiquara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aiuaba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aiuruoca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ajuricaba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoa Grande';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoa Nova';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoinha';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoinha';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoinha do Piaui';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoinhas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alambari';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Albertina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcantara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcantaras';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcantil';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcinopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcobaca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aldeias Altas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alecrim';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alegre';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alegrete';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alegrete do Piaui';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alegria';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alem Paraiba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alenquer';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alexandria';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alexania';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alfenas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alfredo Chaves';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alfredo Marcondes';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alfredo Vasconcelos';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alfredo Wagner';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Algodao de Jandaira';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alhandra';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alianca';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alianca do Tocantins';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almadina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almeirim';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almenara';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almino Afonso';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almirante Tamandare';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almirante Tamandare do Sul';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aloandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alpercata';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alpestre';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alpinopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alta Floresta';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alta Floresta DOeste';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altair';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altamira';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altamira do Maranhao';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altamira do Parana';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altaneira';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alterosa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altinho';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altinopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre do Maranhao';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre do Pindare';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre dos Parecis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Araguaia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Bela Vista';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Boa Vista';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Caparao';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto do Rodrigues';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Feliz';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Garcas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Horizonte';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Jequitiba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Longa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Paraguay';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Paraiso';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Paraiso';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Paraiso de Goias';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Parana';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Parnaiba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Piquiri';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Rio Doce';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Rio Novo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Santo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Taquari';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altonia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altos';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aluminio';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvaraes';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvarenga';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvares Florence';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvares Machado';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvaro de Carvalho';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvinlandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvinopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada de Minas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada do Gurgueia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada do Norte';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada do Sul';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada DOeste';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amajari';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amambai';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amapa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amapa do Maranhao';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amapora';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amaraji';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amaral Ferrador';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amaralina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amarante';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amarante do Maranhao';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amargosa';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amatura';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amelia Rodrigues';
exec SP_INSERT_CIDADE @NM_CIDADE = 'America Dourada';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Americana';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Americano do Brasil';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Americo Brasiliense';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Americo de Campos';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ametista do Sul';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amontada';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amorinopolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amparo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amparo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amparo do Sao Francisco';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amparo do Serra';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ampere';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anadia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anage';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anahy';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anajas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anajatuba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Analandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anama';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ananas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ananindeua';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anapolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anapu';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anapurus';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anastacio';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anaurilandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anchieta';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anchieta';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andarai';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andira';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andorinha';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andradas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andradina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andre da Rocha';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Andrelandia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angatuba';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angelândia';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alta Floresta D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ariquemes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cabixi'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cacoal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cerejeiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colorado do Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Corumbiara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Costa Marques'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Espigão D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guajará-Mirim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaru'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ji-Paraná'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Machadinho D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Brasilândia D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ouro Preto do Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pimenta Bueno'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Velho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Médici'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio Crespo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rolim de Moura'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Luzia D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vilhena'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Miguel do Guaporé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Mamoré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre dos Parecis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Paraíso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buritis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Horizonte do Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cacaulândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campo Novo de Rondônia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Candeias do Jamari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Castanheiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chupinguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cujubim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Jorge Teixeira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapuã do Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ministro Andreazza'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mirante da Serra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monte Negro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova União'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Parecis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pimenteiras do Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Primavera de Rondônia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Felipe D Oeste'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Francisco do Guaporé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Seringueiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Teixeirópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Theobroma'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Urupá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vale do Anari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vale do Paraíso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acrelândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Assis Brasil'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brasiléia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bujari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capixaba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cruzeiro do Sul'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Epitaciolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Feijó'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jordão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mâncio Lima'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Manoel Urbano'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marechal Thaumaturgo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Plácido de Castro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Walter'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio Branco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rodrigues Alves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Rosa do Purus'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Senador Guiomard'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sena Madureira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tarauacá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Xapuri'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Acre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvarães'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amaturá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anamã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anori'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Apuí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Atalaia do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Autazes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barcelos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barreirinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Benjamin Constant'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Beruri'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boa Vista do Ramos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boca do Acre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Borba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caapiranga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Canutama'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Carauari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Careiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Careiro da Várzea'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Coari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Codajás'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Eirunepé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Envira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fonte Boa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guajará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Humaitá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipixuna'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Iranduba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itacoatiara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itamarati'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapiranga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Japurá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Juruá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jutaí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lábrea'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Manacapuru'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Manaquiri'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Manaus'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Manicoré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maraã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maués'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nhamundá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Olinda do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Airão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Aripuanã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Parintins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pauini'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Figueiredo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio Preto da Eva'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Isabel do Rio Negro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Antônio do Içá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Gabriel da Cachoeira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Paulo de Olivença'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Sebastião do Uatumã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Silves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tabatinga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tapauá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tefé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tonantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Uarini'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Urucará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Urucurituba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amajari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boa Vista'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bonfim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cantá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caracaraí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caroebe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Iracema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mucajaí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Normandia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pacaraima'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rorainópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João da Baliza'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Luiz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Uiramutã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abaetetuba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abel Figueiredo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afuá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Azul do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alenquer'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almeirim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altamira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anajás'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ananindeua'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anapu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Augusto Corrêa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aurora do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aveiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bagre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Baião'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bannach'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barcarena'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Belém'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Belterra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Benevides'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Jesus do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bonito'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bragança'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brasil Novo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brejo Grande do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Breu Branco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Breves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bujaru'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cachoeira do Piriá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cachoeira do Arari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cametá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Canaã dos Carajás'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capanema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capitão Poço'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Castanhal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chaves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colares'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Conceição do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Concórdia do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cumaru do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curionópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curralinho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curuá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curuçá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dom Eliseu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Eldorado do Carajás'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Faro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Floresta do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Garrafão do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Goianésia do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Gurupá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Igarapé-Açu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Igarapé-Miri'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Inhangapi'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipixuna do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Irituia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaituba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itupiranga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jacareacanga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jacundá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Juruti'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Limoeiro do Ajuru'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mãe do Rio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Magalhães Barata'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marabá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maracanã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marapanim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marituba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Medicilândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Melgaço'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mocajuba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Moju'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mojuí dos Campos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monte Alegre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Muaná'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Esperança do Piriá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Ipixuna'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Timboteua'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Progresso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Repartimento'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Óbidos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Oeiras do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Oriximiná'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ourém'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ourilândia do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pacajá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palestina do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paragominas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Parauapebas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pau D Arco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Peixe-Boi'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Piçarra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Placas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ponta de Pedras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Portel'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto de Moz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Prainha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Primavera'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Quatipuru'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Redenção'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio Maria'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rondon do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rurópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Salinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Salvaterra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Bárbara do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Cruz do Arari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Izabel do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Luzia do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Maria das Barreiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Maria do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santana do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santarém'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santarém Novo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Antônio do Tauá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Caetano de Odivelas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Domingos do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Domingos do Capim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Félix do Xingu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Francisco do Pará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Geraldo do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João da Ponta'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João de Pirabas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Miguel do Guamá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Sebastião da Boa Vista'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sapucaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Senador José Porfírio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Soure'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tailândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Terra Alta'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Terra Santa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tomé-Açu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tracuateua'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Trairão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tucumã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tucuruí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ulianópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Uruará'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vigia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Viseu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vitória do Xingu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Xinguara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Serra do Navio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amapá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pedra Branca do Amapari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Calçoene'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cutias'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ferreira Gomes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaubal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Laranjal do Jari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Macapá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mazagão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Oiapoque'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pracuúba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santana'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tartarugalzinho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vitória do Jari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abreulândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aguiarnópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aliança do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Almas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ananás'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angico'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aparecida do Rio Negro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aragominas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araguacema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araguaçu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araguaína'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araguanã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araguatins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Arapoema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Arraias'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Augustinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aurora do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Axixá do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Babaçulândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bandeirantes do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barra do Ouro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barrolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bernardo Sayão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Jesus do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brasilândia do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brejinho de Nazaré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buriti do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cachoeirinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campos Lindos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cariri do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Carmolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Carrasco Bonito'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caseara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Centenário'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chapada de Areia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chapada da Natividade'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colinas do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Combinado'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Conceição do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Couto Magalhães'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cristalândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Crixás do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Darcinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dianópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Divinópolis do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dois Irmãos do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dueré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Esperantina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fátima'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Figueirópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Filadélfia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Formoso do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tabocão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Goianorte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Goiatins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guaraí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Gurupi'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipueiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itacajá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaguatins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapiratins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaporã do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaú do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Juarina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa da Confusão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lajeado'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lavandeira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lizarda'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Luzinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marianópolis do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mateiros'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maurilândia do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Miracema do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Miranorte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monte do Carmo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monte Santo do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmeiras do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Muricilândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Natividade'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nazaré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Olinda'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Rosalândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Acordo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Alegre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Jardim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Oliveira de Fátima'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmeirante'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmeirópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paraíso do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paranã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pau D Arco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pedro Afonso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Peixe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pequizeiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colméia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pindorama do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Piraquê'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pium'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ponte Alta do Bom Jesus'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ponte Alta do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Alegre do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Nacional'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Praia Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Kennedy'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pugmil'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Recursolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Riachinho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio da Conceição'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio dos Bois'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio Sono'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sampaio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sandolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Fé do Araguaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Maria do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Rita do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Rosa do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Tereza do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Terezinha do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Bento do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Félix do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Miguel do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Salvador do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Sebastião do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Valério'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Silvanópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sítio Novo do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sucupira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Taguatinga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Taipas do Tocantins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Talismã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tocantínia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tocantinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tupirama'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tupiratins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Wanderlândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Xambioá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Açailândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Afonso Cunha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Doce do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcântara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aldeias Altas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altamira do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Alegre do Pindaré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Parnaíba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amapá do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amarante do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anajatuba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anapurus'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Apicum-Açu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araguanã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araioses'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Arame'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Arari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Axixá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bacabal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bacabeira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bacuri'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bacurituba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Balsas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barão de Grajaú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barra do Corda'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barreirinhas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Belagua'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bela Vista do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Benedito Leite'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bequimão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bernardo do Mearim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boa Vista do Gurupi'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Jardim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Jesus das Selvas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Lugar'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brejo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brejo de Areia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buriti'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buriti Bravo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buriticupu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buritirana'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cachoeira Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cajapió'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cajari'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campestre do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cândido Mendes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cantanhede'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capinzal do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Carolina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Carutapera'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caxias'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cedral'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Central do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Centro do Guilherme'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Centro Novo do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chapadinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cidelândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Codó'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Coelho Neto'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colinas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Conceição do Lago-Açu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Coroatá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cururupu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Davinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dom Pedro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Duque Bacelar'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Esperantinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Estreito'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Feira Nova do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fernando Falcão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Formosa da Serra Negra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fortaleza dos Nogueiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fortuna'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Godofredo Viana'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Gonçalves Dias'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Archer'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Edison Lobão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Eugênio Barros'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Luiz Rocha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Newton Bello'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Governador Nunes Freire'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Graça Aranha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Grajaú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guimarães'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Humberto de Campos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Icatu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Igarapé do Meio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Igarapé Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Imperatriz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaipava do Grajaú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapecuru Mirim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itinga do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jatobá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jenipapo dos Vieiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'João Lisboa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Joselândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Junco do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lago da Pedra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lago do Junco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lago Verde'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa do Mato'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lago dos Rodrigues'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa Grande do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lajeado Novo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lima Campos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Loreto'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Luís Domingues'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Magalhães de Almeida'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maracaçumé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marajá do Sena'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maranhãozinho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mata Roma'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Matinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Matões'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Matões do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Milagres do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mirador'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Miranda do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mirinzal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monção'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Montes Altos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Morros'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nina Rodrigues'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Colinas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Iorque'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Olinda do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Olho d agua das Cunhãs'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Olinda Nova do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paço do Lumiar'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmeirândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paraibano'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Parnarama'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Passagem Franca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pastos Bons'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paulino Neves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paulo Ramos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pedreiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pedro do Rosário'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Penalva'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Peri Mirim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Peritoró'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pindaré-Mirim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pinheiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pio XII'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pirapemas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Poção de Pedras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Franco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Rico do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Dutra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Juscelino'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Médici'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Sarney'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Presidente Vargas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Primeira Cruz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Raposa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Riachão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ribamar Fiquene'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rosário'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sambaíba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Filomena do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Helena'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Inês'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Luzia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Luzia do Paruá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Quitéria do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Rita'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santana do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Amaro do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Antônio dos Lopes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Benedito do Rio Preto'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Bento'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Bernardo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Domingos do Azeitão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Domingos do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Félix de Balsas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Francisco do Brejão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Francisco do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João Batista'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João do Carú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João do Paraíso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João do Soter'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João dos Patos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São José de Ribamar'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São José dos Basílios'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Luís'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Luís Gonzaga do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Mateus do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Pedro da agua Branca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Pedro dos Crentes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Raimundo das Mangabeiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Raimundo do Doca Bezerra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Roberto'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Vicente Ferrer'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Satubinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Senador Alexandre Costa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Senador La Rocque'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Serrano do Maranhão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sítio Novo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sucupira do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sucupira do Riachão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tasso Fragoso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Timbiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Timon'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Trizidela do Vale'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tufilândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tuntum'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Turiaçu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Turilândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tutóia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Urbano Santos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vargem Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Viana'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vila Nova dos Martírios'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vitória do Mearim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vitorino Freire'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Zé Doca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acauã'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agricolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Agua Branca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alagoinha do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alegrete do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Longá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alvorada do Gurguéia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amarante'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angical do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anísio de Abreu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antônio Almeida'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aroazes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aroeiras do Itaim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Arraial'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Assunção do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Avelino Lopes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Baixa Grande do Ribeiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barra D Alcântara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barreiras do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barro Duro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Batalha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bela Vista do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Belém do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Beneditinos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bertolínia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Betânia do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boa Hora'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bocaina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Jesus'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bom Princípio do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bonfim do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boqueirão do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brasileira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brejo do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buriti dos Lopes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Buriti dos Montes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cabeceiras do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cajazeiras do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cajueiro da Praia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caldeirão Grande do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campinas do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campo Alegre do Fidalgo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campo Grande do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campo Largo do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campo Maior'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Canavieira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Canto do Buriti'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capitão de Campos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capitão Gervásio Oliveira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caracol'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caraúbas do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caridade do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Castelo do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caxingó'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cocal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cocal de Telha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cocal dos Alves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Coivaras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colônia do Gurguéia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Colônia do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Conceição do Canindé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Coronel José Dias'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Corrente'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cristalândia do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cristino Castro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curimatá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Currais'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curralinhos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Curral Novo do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Demerval Lobão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dirceu Arcoverde'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dom Expedito Lopes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Domingos Mourão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Dom Inocêncio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Elesbão Veloso'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Eliseu Martins'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Esperantina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fartura do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Flores do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Floresta do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Floriano'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Francinópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Francisco Ayres'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Francisco Macedo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Francisco Santos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fronteiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Geminiano'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Gilbués'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guadalupe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guaribas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Hugo Napoleão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ilha Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Inhuma'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipiranga do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Isaías Coelho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itainópolis'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaueira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jacobina do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaicós'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jardim do Mulato'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jatobá do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jerumenha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'João Costa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Joaquim Pires'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Joca Marques'
exec SP_INSERT_CIDADE @NM_CIDADE = 'José de Freitas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Juazeiro do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Júlio Borges'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jurema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoinha do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa Alegre'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa do Barro do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa de São Francisco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lagoa do Sítio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Landri Sales'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Luís Correia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Luzilândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Madeiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Manoel Emídio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marcolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marcos Parente'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Massapê do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Matias Olímpio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Miguel Alves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Miguel Leão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Milton Brandão'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monsenhor Gil'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monsenhor Hipólito'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Monte Alegre do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Morro Cabeça no Tempo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Morro do Chapéu do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Murici dos Portelas'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nazaré do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nazária'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nossa Senhora de Nazaré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nossa Senhora dos Remédios'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Oriente do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Novo Santo Antônio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Oeiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Olho D agua do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Padre Marcos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paes Landim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pajeú do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmeira do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Palmeirais'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paquetá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Parnaguá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Parnaíba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Passagem Franca do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Patos do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pau D Arco do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Paulistana'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pavussu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pedro II'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pedro Laurentino'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Nova Santa Rita'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Picos'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pimenteiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Pio IX'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Piracuruca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Piripiri'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Porto Alegre do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Prata do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Queimada Nova'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Redenção do Gurguéia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Regeneração'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Riacho Frio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ribeira do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ribeiro Gonçalves'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Rio Grande do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Cruz do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Cruz dos Milagres'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Filomena'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Luz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santana do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santa Rosa do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Antônio de Lisboa'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Antônio dos Milagres'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Santo Inácio do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Braz do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Félix do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Francisco de Assis do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Francisco do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Gonçalo do Gurguéia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Gonçalo do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João da Canabrava'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João da Fronteira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João da Serra'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João da Varjota'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João do Arraial'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São João do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São José do Divino'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São José do Peixe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São José do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Julião'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Lourenço do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Luis do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Miguel da Baixa Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Miguel do Fidalgo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Miguel do Tapuio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Pedro do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'São Raimundo Nonato'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sebastião Barros'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sebastião Leal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sigefredo Pacheco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Simões'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Simplício Mendes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Socorro do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Sussuapara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tamboril do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Tanque do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Teresina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'União'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Uruçuí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Valença do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Várzea Branca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Várzea Grande'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vera Mendes'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Vila Nova do Piauí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Wall Ferraz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Abaiara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acarape'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acaraú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Acopiara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aiuaba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alcântaras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Altaneira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Alto Santo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Amontada'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antonina do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Apuiarés'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aquiraz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aracati'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aracoiaba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ararendá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Araripe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aratuba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Arneiroz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Assaré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Aurora'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Baixio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Banabuiú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barbalha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barreira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Barroquinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Baturité'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Beberibe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Bela Cruz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Boa Viagem'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Brejo Santo'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Camocim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Campos Sales'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Canindé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Capistrano'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caridade'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cariré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caririaçu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cariús'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Carnaubal'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cascavel'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Catarina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Catunda'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Caucaia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cedro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chaval'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Choró'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Chorozinho'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Coreaú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Crateús'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Crato'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Croatá'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Cruz'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Deputado Irapuan Pinheiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ereré'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Eusébio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Farias Brito'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Forquilha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fortaleza'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Fortim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Frecheirinha'
exec SP_INSERT_CIDADE @NM_CIDADE = 'General Sampaio'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Graça'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Granja'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Granjeiro'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Groaíras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guaiúba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guaraciaba do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Guaramiranga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Hidrolândia'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Horizonte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ibaretama'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ibiapina'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ibicuitinga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Icapuí'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Icó'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Iguatu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Independência'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipaporanga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipaumirim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipu'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Ipueiras'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Iracema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Irauçuba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaiçaba'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itaitinga'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapajé'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapipoca'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itapiúna'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itarema'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Itatira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaguaretama'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaguaribara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaguaribe'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jaguaruana'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jardim'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jati'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jijoca de Jericoacoara'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Juazeiro do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Jucás'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Lavras da Mangabeira'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Limoeiro do Norte'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Madalena'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maracanaú'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Maranguape'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Marco'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Martinópole'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Massapê'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Mauriti'
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angelica';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angelim';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angelina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angical';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angical do Piaui';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angico';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angicos';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angra dos Reis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anguera';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Angulo';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anhanguera';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anhembi';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anhumas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anicuns';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anisio de Abreu';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anita Garibaldi';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anitapolis';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anori';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Anta Gorda';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antas';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antonina';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antonina do Norte';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antonio Almeida';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antonio Cardoso';
exec SP_INSERT_CIDADE @NM_CIDADE = 'Antonio Carlos';

SELECT * FROM CIDADE;