/* Criação de tabelas*/
CREATE TABLE BANCO(
	CD_BANCO INT PRIMARY KEY,
	NM_BANCO VARCHAR(255)
);

CREATE TABLE DADOS_BANCARIOS(
	CD_DADOS_BANCARIOS INT PRIMARY KEY,
	CD_CLIENTE INT NOT NULL,
	CD_BANCO INT,
	AGENCIA VARCHAR(50),
	CONTA VARCHAR(50),
	PIX VARCHAR(50),
	CONSTRAINT FK_BANCO_DADOS_BANCARIOS FOREIGN KEY (CD_BANCO) 
		REFERENCES BANCO(CD_BANCO)
);

CREATE TABLE VAL_CONT(
	CD_VALOR_CONTRATO INT PRIMARY KEY,
	CD_CONTRATO INT NOT NULL,
	VL_CONTRATO INT NOT NULL,
	DS_VALOR VARCHAR(50) NOT NULL,
	DT_INICIO_VIGENCIA_VALOR DATE NOT NULL,
	DT_FIM_VIGENCIA_VALOR DATE NOT NULL
);

CREATE TABLE CON_PAG(
	CD_CON_PAG INT PRIMARY KEY,
	DS_CON_PAG VARCHAR(255) NOT NULL,
	CD_CONTRATO INT NOT NULL,
	VL_PAGAR MONEY NOT NULL,
	DT_PAGAMENTO DATETIME NOT NULL,
	CD_AGENTE INT NOT NULL,
	DT_REGISTRO DATETIME NOT NULL
);

CREATE TABLE CON_REC(
	CD_CON_REC INT PRIMARY KEY,
	DS_CON_REC VARCHAR(255) NOT NULL,
	CD_CONTRATO INT NOT NULL,
	VL_RECEBER MONEY NOT NULL,
	DT_RECEBIMENTO DATETIME NOT NULL,
	CD_AGENTE INT NOT NULL,
	DT_REGISTRO DATE
);

CREATE TABLE CONTRATOS(
	CD_CONTRATO INT PRIMARY KEY,
	DS_CONTRATO VARCHAR(255) NOT NULL,
	TP_CONTRATO VARCHAR(1) NOT NULL,
	CD_CONTRATANTE INT NOT NULL,
	CD_LOCATARIO INT NOT NULL,
	CD_AGENTE VARCHAR(50) NOT NULL,
	DT_REGISTRO_CONTRATO DATETIME NOT NULL,
	DT_INICIO_CONTRATO DATE NOT NULL,
	DT_FIM_CONTRATO DATE NOT NULL,
	DT_VENCIMENTO_CONTRATO DATE NOT NULL
);

CREATE TABLE CLIENTE (
	CD_CLIENTE INT PRIMARY KEY,
	NM_CLIENTE VARCHAR(50) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	CD_USUARIO_CADASTRO VARCHAR(50),
	CPF VARCHAR(14) NOT NULL,
	TP_SEXO VARCHAR(1),
	TP_ESTADO_CIVIL VARCHAR(1) DEFAULT 'S' NOT NULL,
	NR_CELULAR VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(50),
	RG VARCHAR(80),
	DT_CADASTRO DATETIME,
	DS_OBSERVACAO VARCHAR(255)
);

CREATE TABLE ENDERECO_CLIENTE(
	CD_ENDERECO INT PRIMARY KEY,
	CD_CLIENTE INT NOT NULL,
	NR_CEP INT,
	DS_ENDERECO VARCHAR(255) NOT NULL,
	NR_ENDERECO INT NOT NULL,
	DS_COMPLEMENTO VARCHAR(255),
	NM_BAIRRO VARCHAR(255),
	NM_CIDADE VARCHAR(255),
	NM_PAIS VARCHAR(30) DEFAULT 'BRASIL' NOT NULL,
	CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY (CD_CLIENTE) 
		REFERENCES CLIENTE (CD_CLIENTE)
);


/* Sequencias das tabelas*/
CREATE SEQUENCE SEQ_BANCO
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_DADOS_BANCARIOS
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_VAL_CONT
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_CON_PAG
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_CON_REC
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_CONTRATOS
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_CLIENTE
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;

CREATE SEQUENCE SEQ_ENDERECO_CLIENTE
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9999999
	CACHE 10;


/* Alterações de tabelas*/
ALTER TABLE CON_PAG
ADD CONSTRAINT FK_CON_PAG_CONT FOREIGN KEY (CD_CONTRATO)
REFERENCES CONTRATOS (CD_CONTRATO);

ALTER TABLE CON_REC
ADD CONSTRAINT FK_CON_REC_CONT FOREIGN KEY (CD_CONTRATO)
REFERENCES CONTRATOS (CD_CONTRATO);

ALTER TABLE DADOS_BANCARIOS
ADD CONSTRAINT FK_DADOS_BANCARIOS_CLIENTE FOREIGN KEY (CD_CLIENTE)
REFERENCES CLIENTE (CD_CLIENTE);

ALTER TABLE CONTRATOS
ADD CONSTRAINT FK_CONTRATANTE FOREIGN KEY (CD_CONTRATANTE)
REFERENCES CLIENTE (CD_CLIENTE);

ALTER TABLE CONTRATOS
ADD CONSTRAINT FK_LOCATARIO FOREIGN KEY (CD_LOCATARIO)
REFERENCES CLIENTE (CD_CLIENTE);

ALTER TABLE VAL_CONT
ADD CONSTRAINT FK_CONTRATOS_VALOR_CONTRATOS FOREIGN KEY(CD_CONTRATO)
		REFERENCES CONTRATOS (CD_CONTRATO);

EXEC sp_addextendedproperty 
    @name = N'MS_Description',
    @value = N'S - Solteiro; C - Casado; E - Separado; D - Divorciado; V - Viuvo; U - Uniao estavel',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE', @level1name = 'CLIENTE',
    @level2type = N'COLUMN', @level2name = 'TP_ESTADO_CIVIL';

EXEC sp_addextendedproperty 
    @name = N'MS_Description',
    @value = N'R - Residencia; C - Comercial; R - Rural; O - Corretagem; F - Financiamento Imobiliario; B - Built-to-suit; E - Cessao de direitos possessorios; A - Arrendamento Rural; I - Incorporação Imobiliaria; M - Comodato; ',
    @level0type = N'SCHEMA', @level0name = 'dbo',
    @level1type = N'TABLE', @level1name = 'CONTRATOS',
    @level2type = N'COLUMN', @level2name = 'TP_CONTRATO';
