CREATE TABLE BANCO(
	CD_BANCO INT PRIMARY KEY,
	NM_BANCO VARCHAR(255)
);


CREATE TABLE DADO_BANCARIOS(
	CD_DADOS_BANCARIOS INT PRIMARY KEY,
	CD_CLIENTE INT,
	CD_BANCO INT,
	AGENCIA VARCHAR(50),
	CONTA VARCHAR(50),
	PIX VARCHAR(50)
	FOREIGN KEY (CD_BANCO) REFERENCES BANCO(CD_BANCO)
);

CREATE TABLE PAIS(
	CD_PAIS INT PRIMARY KEY,
	NM_PAIS NVARCHAR
);

