CREATE OR ALTER PROCEDURE SP_INSERT_CLIENTE
    @NM_CLIENTE VARCHAR(50),
    @DT_NASCIMENTO DATE,
    @NR_CPF VARCHAR(14),
    @TP_SEXO VARCHAR(1) = 'I',
    @TP_ESTADO_CIVIL VARCHAR(1),
    @NR_CELULAR VARCHAR(16),
    @EMAIL VARCHAR(50) = '',
    @RG VARCHAR(50) = '',
    @DS_OBSERVACAO VARCHAR(255) = ''
AS
BEGIN
    -- Verifica se já existe um cliente com o mesmo CPF
    IF EXISTS (
        SELECT 1
        FROM DBO.CLIENTE
        WHERE CPF = @NR_CPF
    ) 
    BEGIN 
        -- Levanta um erro se o CPF já existir na base de dados
        RAISERROR('Já existe um registro com o mesmo CPF.', 16, 1);
    END
    ELSE
    BEGIN
        -- Insere um novo cliente na tabela CLIENTE
        INSERT INTO DBO.CLIENTE (CD_CLIENTE, NM_CLIENTE, DT_NASCIMENTO, CD_USUARIO_CADASTRO, CPF, TP_SEXO, TP_ESTADO_CIVIL, NR_CELULAR, EMAIL, RG, DT_CADASTRO, DS_OBSERVACAO)
        VALUES (NEXT VALUE FOR SEQ_CLIENTE, @NM_CLIENTE, @DT_NASCIMENTO, SUSER_SNAME(), @NR_CPF, @TP_SEXO, @TP_ESTADO_CIVIL, @NR_CELULAR, @EMAIL, @RG, GETDATE(), @DS_OBSERVACAO);
    END;
END;

GO

CREATE OR ALTER PROCEDURE SP_INSERT_ENDERECO_CLIENTE
	@CD_CLIENTE INT,
	@NR_CEP INT,
	@DS_ENDERECO VARCHAR(255),
	@NR_ENDERECO INT,
	@DS_COMPLEMENTO VARCHAR(255) = '',
	@NM_BAIRRO VARCHAR(255) = '',
	@NM_CIDADE VARCHAR(255) = '',
	@NM_PAIS VARCHAR(30) = 'BRASIL'
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM DBO.ENDERECO_CLIENTE
		WHERE CD_CLIENTE = @CD_CLIENTE
	)
	BEGIN
		RAISERROR('Já existe um registro para o mesmo cliente na mesma localidade.', 16, 1);
		RETURN;
	END
	ELSE
	BEGIN
		INSERT INTO DBO.ENDERECO_CLIENTE(CD_ENDERECO, CD_CLIENTE, NR_CEP, DS_ENDERECO, NR_ENDERECO, DS_COMPLEMENTO, NM_BAIRRO, NM_CIDADE, NM_PAIS)
		VALUES (NEXT VALUE FOR SEQ_ENDERECO_CLIENTE, @CD_CLIENTE, @NR_CEP, @DS_ENDERECO, @NR_ENDERECO, @DS_COMPLEMENTO, @NM_BAIRRO, @NM_CIDADE, @NM_PAIS)
	END;
END;