CREATE OR ALTER PROCEDURE SP_INSERT_CLIENTE
    @NM_CLIENTE VARCHAR(50),
    @DT_NASCIMENTO DATE,
    @NR_CPF VARCHAR(14),
    @TP_SEXO VARCHAR(1) = 'I',
    @TP_ESTADO_CIVIL VARCHAR(1),
    @NR_CELULAR VARCHAR(16),
    @EMAIL VARCHAR(50) = '',
    @RG VARCHAR(50) = '',
    @DS_OBSERVACAO VARCHAR(255) = '',
	-- Variaves de dados bancarios
	@CD_BANCO INT,
	@AGENCIA VARCHAR(50),
	@CONTA VARCHAR (50),
	@PIX VARCHAR(50),
	-- Variaveis de endereço
	@NR_CEP INT,
	@DS_ENDERECO VARCHAR(255),
	@NR_ENDERECO INT,
	@DS_COMPLEMENTO VARCHAR(255) = '',
	@NM_BAIRRO VARCHAR(255) = '',
	@NM_CIDADE VARCHAR(255) = '',
	@NM_PAIS VARCHAR(30) = 'BRASIL'
AS
BEGIN
    -- Verifica se já existe um cliente com o mesmo CPF
    IF EXISTS (
        SELECT 1
        FROM DBO.CLIENTE
        WHERE CPF = @NR_CPF
    ) 
    BEGIN 
        -- Levanta um erro se o CPF já existir na base de dados
        RAISERROR('Já existe um registro com o mesmo CPF.', 16, 1);
    END
    ELSE
    BEGIN
		-- Guarda o valor da proxima sequencia de cliente em varivel para ser reutilizada.
		DECLARE @CD_CLIENTE INT;
		SET @CD_CLIENTE = NEXT VALUE FOR SEQ_CLIENTE;
		
        -- Insere um novo cliente na tabela CLIENTE
        INSERT INTO DBO.CLIENTE (CD_CLIENTE, NM_CLIENTE, DT_NASCIMENTO, CD_USUARIO_CADASTRO, CPF, TP_SEXO, TP_ESTADO_CIVIL, NR_CELULAR, EMAIL, RG, DT_CADASTRO, DS_OBSERVACAO)
        VALUES (@CD_CLIENTE, @NM_CLIENTE, @DT_NASCIMENTO, SUSER_SNAME(), @NR_CPF, @TP_SEXO, @TP_ESTADO_CIVIL, @NR_CELULAR, @EMAIL, @RG, GETDATE(), @DS_OBSERVACAO);
		
		-- Insere um novo cliente na tabela DADOS_BANCARIOS
		INSERT INTO DBO.DADOS_BANCARIOS (CD_DADOS_BANCARIOS, CD_CLIENTE, CD_BANCO, AGENCIA, CONTA, PIX)
		VALUES (NEXT VALUE FOR SEQ_DADOS_BANCARIOS, @CD_CLIENTE, @CD_BANCO, @AGENCIA, @CONTA, @PIX);

		-- Insere endereco do novo cliente
		INSERT INTO DBO.ENDERECO_CLIENTE(CD_ENDERECO, CD_CLIENTE, NR_CEP, DS_ENDERECO, NR_ENDERECO, DS_COMPLEMENTO, NM_BAIRRO, NM_CIDADE, NM_PAIS)
		VALUES (NEXT VALUE FOR SEQ_ENDERECO_CLIENTE, @CD_CLIENTE, @NR_CEP, @DS_ENDERECO, @NR_ENDERECO, @DS_COMPLEMENTO, @NM_BAIRRO, @NM_CIDADE, @NM_PAIS)
    END;
END;

GO

CREATE OR ALTER PROCEDURE SP_INSERT_CONTRATOS
	@DS_CONTRATO VARCHAR(255) = 'TESTE DE CONTRATO 001',
	@TP_CONTRATO VARCHAR (1) = 'L',
	@CD_CONTRATANTE INT,
	@CD_LOCATARIO INT,
	@DT_INICIO_CONTRATO DATE,
	@DT_FIM_CONTRATO DATE,
	@DT_VENCIMENTO_CONTRATO DATE,
	@VL_CONTRATO INT,
	@DS_VALOR VARCHAR(50),
	@DT_INICIO_VIGENCIA_VALOR DATE,
	@DT_FIM_VIGENCIA_VALOR DATE
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM DBO.CONTRATOS
		WHERE CD_CONTRATANTE = @CD_CONTRATANTE
		AND CD_LOCATARIO = @CD_LOCATARIO
	)
	BEGIN
		RAISERROR('Já existe um registro para o mesmo contrato.', 16, 1);
		RETURN;
	END
	ELSE
	BEGIN
		-- Guarda o proximo valor da sequencia de contrato dentro de uma varivavel
		DECLARE @CD_CONTRATO INT;
		SET @CD_CONTRATO = NEXT VALUE FOR SEQ_CONTRATOS;

		-- Insere um novo contrato na tabela CONTRATOS
		INSERT INTO DBO.CONTRATOS (CD_CONTRATO, DS_CONTRATO, TP_CONTRATO, CD_CONTRATANTE, CD_LOCATARIO, CD_AGENTE, DT_REGISTRO_CONTRATO, DT_INICIO_CONTRATO, DT_FIM_CONTRATO, DT_VENCIMENTO_CONTRATO)
		VALUES (@CD_CONTRATO, @DS_CONTRATO, @TP_CONTRATO, @CD_CONTRATANTE, @CD_LOCATARIO, SUSER_SNAME(), GETDATE(), @DT_INICIO_CONTRATO, @DT_FIM_CONTRATO, @DT_VENCIMENTO_CONTRATO);

		-- Insere um novo valor de contrato na tabela VAl_CONT
		INSERT INTO DBO.VAL_CONT (CD_VALOR_CONTRATO, CD_CONTRATO, VL_CONTRATO, DS_VALOR, DT_INICIO_VIGENCIA_VALOR, DT_FIM_VIGENCIA_VALOR)
		VALUES (NEXT VALUE FOR SEQ_VAL_CONT, @CD_CONTRATO, @VL_CONTRATO, @DS_CONTRATO, @DT_INICIO_VIGENCIA_VALOR, @DT_FIM_VIGENCIA_VALOR);
	END;
END;

GO

CREATE OR ALTER PROCEDURE SP_INSERT_BANCO
	@NM_BANCO VARCHAR(255)
AS
BEGIN
	IF EXISTS(
		SELECT 1
		FROM DBO.BANCO
		WHERE NM_BANCO = @NM_BANCO
	)
	BEGIN
		RAISERROR('Já existe um banco com esse mesmo nome cadastrado.', 16, 1);
		RETURN;
	END
	ELSE
	BEGIN
		INSERT INTO DBO.BANCO(CD_BANCO,NM_BANCO)
		VALUES (NEXT VALUE FOR SEQ_BANCO, @NM_BANCO);
	END;
END;