/* Triggers */
CREATE OR ALTER TRIGGER TRG_INSERT_CLIENTE
ON CLIENTE
AFTER INSERT
AS
BEGIN
	UPDATE C
	SET C.NM_CLIENTE = UPPER(dbo.FN_REMOVER_ASCENTUACAO(C.NM_CLIENTE)),
		C.EMAIL = UPPER(C.EMAIL),
		C.DS_OBSERVACAO = UPPER(C.DS_OBSERVACAO),
		C.CPF = UPPER(C.CPF),
		C.RG = UPPER(C.RG)
	FROM CLIENTE C
	INNER JOIN INSERTED I ON C.CD_CLIENTE = I.CD_CLIENTE;
END;

go

CREATE OR ALTER TRIGGER TRG_INSERT_ENDERECO_CLIENTE
ON ENDERECO_CLIENTE
AFTER INSERT
AS
BEGIN
	UPDATE EC
	SET EC.DS_ENDERECO = UPPER(dbo.FN_REMOVER_ASCENTUACAO(EC.DS_ENDERECO)),
		EC.DS_COMPLEMENTO = UPPER(EC.DS_COMPLEMENTO),
		EC.NM_BAIRRO = UPPER(EC.NM_BAIRRO),
		EC.NM_CIDADE = UPPER(EC.NM_CIDADE),
		EC.NM_PAIS = UPPER(EC.NM_PAIS)
	FROM ENDERECO_CLIENTE EC
	INNER JOIN INSERTED I ON EC.CD_ENDERECO = I.CD_ENDERECO;
END;

GO

CREATE OR ALTER TRIGGER TRG_INSERT_CONTRATOS
ON CONTRATOS
AFTER INSERT
AS
BEGIN
	UPDATE C
	SET C.DS_CONTRATO = UPPER(C.DS_CONTRATO),
		C.TP_CONTRATO = UPPER(C.TP_CONTRATO)
	FROM CONTRATOS C
	INNER JOIN INSERTED I ON C.CD_CONTRATO = I.CD_CONTRATO;
END;

GO

CREATE OR ALTER TRIGGER TRG_INSERT_VAL_CONT
ON VAL_CONT
AFTER INSERT
AS
BEGIN
	UPDATE VC
	SET VC.DS_VALOR = UPPER(VC.DS_VALOR)
	FROM VAL_CONT VC
	INNER JOIN INSERTED I ON VC.CD_VALOR_CONTRATO = I.CD_VALOR_CONTRATO;
END;

GO

CREATE OR ALTER TRIGGER TRG_INSERT_BANCO
ON BANCO
AFTER INSERT
AS
BEGIN
	UPDATE B
	SET B.NM_BANCO = UPPER(B.NM_BANCO)
	FROM BANCO B
	INNER JOIN INSERTED I ON B.CD_BANCO = I.CD_BANCO;
END;
